# Generated by Django 4.0.6 on 2023-10-31 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='slung',
            new_name='slug',
        ),
    ]
